spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      # 因为mysql使用schema标识库名而不是catalog，因此mysql会扫描所有的库来找表，如果其他库中有相同名称的表，activiti就以为找到了，本质上这个表在当前数据库中并不存在
      url: jdbc:mysql://192.168.5.137:3306/emos?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
      username: root
      password: 1234
      initial-size: 2
      max-active: 4
      min-idle: 4
      max-wait: 60000
      test-while-idle: false
      test-on-borrow: true
      test-on-return: false
  redis:
    database: 1
    host: 192.168.5.137
    port: 6379
    password: 1234
    jedis:
      pool:
        max-active: 1000
        max-wait: -1ms
        max-idle: 16
        min-idle: 8
  activiti:
    # 1.false：默认值。activiti在启动时，对比数据库表中保存的版本，如果没有表或者版本不匹配，将抛出异常
    # 2.true： activiti会对数据库中所有表进行更新操作。如果表不存在，则自动创建
    # 3.create_drop： 在activiti启动时创建表，在关闭时删除表（必须手动关闭引擎，才能删除表）
    # 4.drop-create： 在activiti启动时删除原来的旧表，然后在创建新表（不需要手动关闭引擎）
    database-schema-update: true

    # 检测历史表是否存在 activiti7默认没有开启数据库历史记录 启动数据库历史记录
    db-history-used: true

    # 记录历史等级 可配置的历史级别有none, activity, audit, full
    # none：不保存任何的历史数据，因此，在流程执行过程中，这是最高效的。
    # activity：级别高于none，保存流程实例与流程行为，其他数据不保存。
    # audit：除activity级别会保存的数据外，还会保存全部的流程任务及其属性。audit为history的默认值。
    # full：保存历史数据的最高级别，除了会保存audit级别的数据外，还会保存其他全部流程相关的细节数据，包括一些流程参数等。
    history-level: full

    # 校验流程文件，默认校验resources下的processes文件夹里的流程文件
    check-process-definitions: true

    # 关闭自动部署
    deployment-mode: never-fail

    # 解决频繁查询SQL问题
    async-executor-activate: false

  quartz:
    job-store-type: jdbc

  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    protocol: smtp
    port: 465
    username: dsferg4534@163.com
    password: 12345678
    properties:
      mail:
        smtp:
          ssl:
            enable: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.emos.workflow.db.pojo
  configuration:
    map-underscore-to-camel-case: true
